/**
 * SYSTEMMETRICS CLASS - Performance Monitoring Data
 *
 * PURPOSE:
 * - Stores system-wide performance and operational statistics
 * - Enables monitoring of swarm system health and efficiency
 * - Provides data for performance optimization and debugging
 *
 * CORE METRICS:
 * 1. totalAgents - Total number of agents in system
 * 2. activeAgents - Number of agents with ACTIVE status
 * 3. averageSpeed - Mean velocity magnitude across all agents
 * 4. systemLoad - CPU/processing load percentage (0.0-1.0)
 * 5. updatesPerSecond - Simulation update frequency (target: 30-60)
 * 6. memoryUsage - System memory consumption (0.0-1.0)
 *
 * CALCULATION LOGIC:
 * - activeAgents: count of agents where status == AgentStatus.ACTIVE
 * - averageSpeed: sum(agent.velocity.magnitude()) / totalAgents
 * - systemLoad: processing time / available time per frame
 * - updatesPerSecond: actual measured update frequency
 * - memoryUsage: (used memory / total memory)
 *
 * EXPECTED VALUE RANGES:
 * - totalAgents: 0 to system limit (typically 100-1000)
 * - activeAgents: 0 to totalAgents
 * - averageSpeed: 0.0 to maxSpeed (typically 0-50 units/sec)
 * - systemLoad: 0.0 (idle) to 1.0 (100% CPU)
 * - updatesPerSecond: target 30-60, acceptable 15-120
 * - memoryUsage: 0.0 to 1.0 (warning if > 0.8)
 *
 * USAGE EXAMPLES:
 * - SystemMetrics metrics = new SystemMetrics();
 * - metrics.totalAgents = 50;
 * - metrics.activeAgents = 47;
 * - metrics.averageSpeed = 23.5;
 * - if (metrics.systemLoad > 0.8) { reduceUpdateFrequency(); }
 *
 * MONITORING ALERTS:
 * - systemLoad > 0.9: Performance warning
 * - updatesPerSecond < 20: Simulation running slowly
 * - memoryUsage > 0.8: Memory pressure
 * - activeAgents / totalAgents < 0.7: Many agents offline
 *
 * INTEGRATION:
 * - Generated by AgentManager.getVisualizationUpdate()
 * - Consumed by monitoring dashboards
 * - Used for automatic performance tuning
 * - Logged for system analysis and debugging
 */
package com.team6.swarm.core;

public class SystemMetrics {
    public int totalAgents;
    public int activeAgents;
    public double averageSpeed;
    public double systemLoad;
    public int updatesPerSecond;
    public double memoryUsage;
    
    public SystemMetrics() {
        // Initialize with defaults
    }
}